name: Main CICD

env:
  SOLUTION_PATH: GithubAction.sln
  
on:
  workflow_dispatch:
  push:
    branches: [ main , release** ]
  pull_request:
    branches: [ main , release** ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        echo "Cleaning workspace directory..."
        sudo rm -rfv ${{ github.workspace }}
        mkdir -p ${{ github.workspace }}

    - uses: actions/checkout@v3

  build-scan:
    runs-on: ubuntu-latest
    needs:
    - checkout

    steps:
    - name: setup .net core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: check sonar scanner
      id: sonar
      run: echo "FOUND=$(dotnet tool list --global | grep -c 'sonarscanner')" >> $GITHUB_OUTPUT

    - name: install sonar scanner (if runner doesn't have)
      if: steps.sonar.outputs.FOUND == 0
      run: dotnet tool install --global dotnet-sonarscanner

    - name: check sonar scanner after installation
      id: sonar2
      run: echo "FOUND=$(dotnet tool list --global | grep -c 'sonarscanner')" >> $GITHUB_OUTPUT

    - name: echo if sonar already installed
      if: steps.sonar2.outputs.FOUND == 1
      run: echo "Hello Sonar"
      